config/routes.rb
Rails.application.routes.draw do
  
  resources :labels, only: [:show]

  resources :topics do
    
  resources :posts, except: [:index]
end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  
  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
     <ul class="nav nav-tabs">
    <li><%= link_to "Bloccit", root_path %></li>
    <li><%= link_to "Topics", topics_path %></li>
    <li><%= link_to "About", about_path %></li>
    
    <div class="pull-right user-info">
         <% if current_user %>
           <%= current_user.name %> - <%= link_to "Sign Out", session_path(current_user), method: :delete %>
         <% else %>
           <%= link_to "Sign In", new_session_path %> or
           <%= link_to "Sign Up", new_user_path %>
         <% end %>
    </div>
  </ul>
  
  <%  if flash[:notice] %>
      <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
      </div>
      <% elsif flash[:alert] %>
          <div type="button" class="close" data-dismiss="alert">&times;</button>
          </div>
  <% end %>
  
<%= yield %>
 </div>
 
</body>
</html>